version: "3"

services:
  backend:
    container_name: backend
    restart: unless-stopped
    build: ./marker-cluster-server
    ports:
      - "3333:3333"
    env_file: ./marker-cluster-server/.env
    environment:
      - NODE_ENV=production
    networks:
      - internal
  
  frontend:
    container_name: frontend
    restart: unless-stopped
    build: ./marker-cluster-web
    # o path /app se refere ao WORKDIR dentro do Dockerfile do frontend
    environment:
      - NODE_PATH=/app/src
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - internal


networks:
  internal:
