version: "2"
services:
  client:
    image: marker-cluster-client
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./marker-cluster-web:/marker-cluster-web
      - /marker-cluster-web/node_modules
    links:
      - api
    networks:
      - webappnetwork
  api:
    image: marker-cluster-api
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - ./marker-cluster-server:/marker-cluster-server
      - /marker-cluster-server/node_modules
    networks:
      - webappnetwork
networks:
  webappnetwork:
    driver: bridge
